server :
 port : 8090
logging :
 level.cn.itcast : info
#默认为elasticsearch
spring:
 profiles: test
 data.elasticsearch.cluster-name: elasticsearch
#配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
 #data.elasticsearch.cluster-nodes: 127.0.0.1:9300
properties:
 path:
 #elasticsearch日志存储目录
 logs: ./elasticsearch/log
 #elasticsearch数据存储目录
 data: ./elasticsearch/data