server :
 port : 8090
logging :
 level.cn.itcast : info
#默认为elasticsearch
spring:
 data:
  elasticsearch:
   # 集群名
   cluster-name: syncwt-es
   # 连接节点,注意在集群中通信都是9300端口，否则会报错无法连接上！
   cluster-nodes: localhost:9300,119.29.38.169:9300
   # 是否本地连接
   local: false
   repositories:
    # 仓库中数据存储
    enabled: true
spring:
 profiles: test
 data.elasticsearch.cluster-name: elasticsearch
#配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
 #data.elasticsearch.cluster-nodes: 127.0.0.1:9300
properties:
 path:
 #elasticsearch日志存储目录
 logs: ./elasticsearch/log
 #elasticsearch数据存储目录
 data: ./elasticsearch/data